"""empty message

Revision ID: 47e2cba2ee99
Revises: 3895909864b9
Create Date: 2017-03-12 04:54:47.858752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47e2cba2ee99'
down_revision = '3895909864b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('profile_image', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'profile_image')
    # ### end Alembic commands ###
